### PR TITLE
[ADR] create ADR for gRPC usage

### PR DESCRIPTION
**Pull request by mitro**

### CODE REVIEW

**Comment by sergey-rubtsov-05** [comment]
What do you think about storing documentation in `{repositoryRoot}/backend/documentation`? If we use that way we don't need an additional `backend` folder. Also, it is more intuitive when someone needs documentation for the backend he will start from the backend folder. Or will it not be good when we need documentation for the system as a whole (frontend and backend)?

**Comment by sergey-rubtsov-05** [comment]
What do you think about using `ADRs` folder instead of `decisions`? I think it is a more expected name, ADR - is established term.

**Comment by sergey-rubtsov-05** [comment]
May we use zero `ADR` for `MADR`, like here https://github.com/adr/madr/blob/develop/template/0000-use-markdown-architectural-decision-records.md? If so everyone will be easy to understand which pattern we use for `ADR`.

**Comment by mitro** [comment]
> What do you think about storing documentation in `{repositoryRoot}/backend/documentation`? If we use that way we don't need an additional `backend` folder. Also, it is more intuitive when someone needs documentation for the backend he will start from the backend folder. Or will it not be good when we need documentation for the system as a whole (frontend and backend)?

This folder will contain all the documentation for both backend and frontend, so it is better to locate it in the root folder.

**Comment by mitro** [comment]
> What do you think about using `ADRs` folder instead of `decisions`? I think it is a more expected name, ADR - is established term.

This folder name is specified in the MADR description: https://adr.github.io/madr/#usage-of-categories. However, I think it is okay to rename it. I propose to use lowercase to be consistent so that the name will read "adrs".

**Comment by mitro** [comment]
> May we use zero `ADR` for `MADR`, like here https://github.com/adr/madr/blob/develop/template/0000-use-markdown-architectural-decision-records.md? If so everyone will be easy to understand which pattern we use for `ADR`.

Good idea, I will create it in this PR.

**Comment by sergey-rubtsov-05** [comment]
> This folder name is specified in the MADR description: https://adr.github.io/madr/#usage-of-categories. However, I think it is okay to rename it. I propose to use lowercase to be consistent so that the name will read "adrs".

Okay, but now I am not sure that `adrs` is better than `decisions`, I missed that moment in `MADR` specification.

**Review by sergey-rubtsov-05 — APPROVED** [review]
It looks perfect. ADRs give a huge amount of useful information.

**Pull request merged**
